# Generated by Django 5.1.2 on 2024-10-19 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_app', '0002_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='location',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='message',
        ),
        migrations.AddField(
            model_name='alert',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='emergency_type',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Help', 'Help')], default='Emergency', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
